export const categories = {
  technology: [
    "technology",
    "Futurology",
    "OpenAI",
    "artificial",
    "MachineLearning",
    "programming",
    "coding",
    "webdev",
    "devops",
    "cybersecurity",
  ],
  science: [
    "science",
    "Physics",
    "Space",
    "chemistry",
    "biology",
    "math",
    "astronomy",
    "neuroscience",
    "geology",
    "environment",
  ],
  politics: [
    "politics",
    "worldnews",
    "geopolitics",
    "europe",
    "news",
    "politicaldiscussion",
    "conservative",
    "liberal",
    "democrats",
    "republicans",
  ],
  finance: [
    "finance",
    "cryptocurrency",
    "stocks",
    "investing",
    "personalfinance",
    "wallstreetbets",
    "economics",
    "bitcoin",
    "ethereum",
    "trading",
  ],
  gaming: [
    "gaming",
    "pcgaming",
    "gamedev",
    "PS5",
    "XboxSeriesX",
    "NintendoSwitch",
    "Steam",
    "indiegaming",
    "esports",
    "gamingnews",
  ],
  health: [
    "health",
    "medicine",
    "Fitness",
    "nutrition",
    "mentalhealth",
    "yoga",
    "weightlifting",
    "running",
    "diet",
    "wellness",
  ],
  entertainment: [
    "movies",
    "television",
    "music",
    "books",
    "comics",
    "anime",
    "netflix",
    "marvel",
    "starwars",
    "gaming",
  ],
  sports: [
    "sports",
    "nba",
    "nfl",
    "soccer",
    "baseball",
    "hockey",
    "tennis",
    "formula1",
    "golf",
    "cricket",
  ],
  education: [
    "education",
    "college",
    "university",
    "teaching",
    "learnprogramming",
    "math",
    "science",
    "history",
    "philosophy",
    "literature",
  ],
  lifestyle: [
    "food",
    "travel",
    "fashion",
    "beauty",
    "home",
    "gardening",
    "cooking",
    "photography",
    "art",
    "design",
  ],
  business: [
    "business",
    "entrepreneur",
    "startups",
    "marketing",
    "sales",
    "smallbusiness",
    "consulting",
    "management",
    "careers",
    "jobs",
  ],
  social: [
    "socialmedia",
    "privacy",
    "technology",
    "internet",
    "webdev",
    "programming",
    "cybersecurity",
    "datahoarder",
    "netsec",
    "hacking",
  ],
} as const;

export type Category = keyof typeof categories;
